#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# The credentials the release workflow publishes with (#48): trusted publishers on npm and PyPI,
# so no long-lived token is stored anywhere. npm can only trust a package that already exists, so
# the first release goes out with a 7-day token, and a re-run after it swaps that token for
# trusted publishers. Stages already done offer a skip.

TOTAL_STAGES=7

# The repository PyPI trusts and the secret lands in. Named rather than read off the working
# directory, so a fork or an extra remote can't send the secret somewhere else. gh reads GH_REPO.
export GH_REPO="YongboYu/legible-slides"
NPM_PACKAGES=("slidev-theme-legible" "create-legible-slides")
PYPI_PROJECT="legible-slides"
RELEASE_WORKFLOW="release.yml"
PYPI_ENVIRONMENT="pypi"
ENVIRONMENT_BY_HAND="GitHub environment $PYPI_ENVIRONMENT (Settings → Environments → New environment)"

# ok "..." — a line confirming something is in place.
ok() { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }

# has_secret NAME — whether the repository already holds an Actions secret by that name.
has_secret() {
  gh secret list --json name --jq '.[].name' | grep -qxF "$1"
}

# has_environment NAME — whether the repository already has a deployment environment by that name.
has_environment() {
  gh api "repos/$GH_REPO/environments/$1" >/dev/null 2>&1
}

# check_name_free REGISTRY URL NAME — report whether NAME is still unclaimed, from a GET on URL.
check_name_free() {
  local status
  status=$(curl -s -o /dev/null -w '%{http_code}' "$2" || true)
  case "$status" in
    404) ok "$3 is free on $1" ;;
    200) note "$3 exists on $1. Fine if you published it; if not, someone else has the name." ;;
    *)   warn "Couldn't reach $1 to check $3." ;;
  esac
}

# all_on_npm — whether every npm package has been published, which is what lets npm trust it.
all_on_npm() {
  local package status
  for package in "${NPM_PACKAGES[@]}"; do
    status=$(curl -s -o /dev/null -w '%{http_code}' "https://registry.npmjs.org/$package" || true)
    [[ "$status" == 200 ]] || return 1
  done
}

# Every check below asks gh, and a gh that isn't signed in would make each one read as "missing".
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  printf '%sThis wizard needs the GitHub CLI, signed in: install gh, then run gh auth login.%s\n' \
    "$RED" "$RESET" >&2
  exit 1
fi

# Every stage waits on an answer. Without a terminal to type into, each read comes back empty and
# the wizard would race through, so it stops here instead.
if [[ ! -t 0 ]]; then
  printf '%sRun this in a terminal you can type into: it asks questions at every stage.%s\n' \
    "$RED" "$RESET" >&2
  exit 1
fi

banner "Publishing setup: npm and PyPI"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "npm: an account that can publish"
say "The theme and the create package publish under your npm account."
if confirm "Do you already have an npm account with a verified email and two-factor auth on?"; then
  note "Skipping ahead."
else
  open_url "https://www.npmjs.com/signup"
  step "Sign up, or sign in if you have an account."
  step "Verify your email from the message npm sends. npm won't publish from an unverified account."
  step "Profile picture → Account → Two-Factor Authentication → enable it."
  pause "Press Enter once your email is verified and 2FA is on."
fi
NPM_USER=""
for _ in 1 2 3; do
  ask NPM_USER "Your npm username:"
  [[ -n "$NPM_USER" ]] && break
done
if [[ -z "$NPM_USER" ]]; then
  warn "No username given, so the token page can't be opened. Re-run when you have it."
  exit 1
fi

# Asked once: stages 2, 3 and 7 all turn on it.
PUBLISHED=no
all_on_npm && PUBLISHED=yes

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "npm: a one-week token for the first release"
if [[ "$PUBLISHED" == yes ]]; then
  say "Both packages are on npm, so releases publish through trusted publishing (next stage)."
  note "No token needed. Skipping ahead."
else
  say "npm can only trust a package that already exists, so the first release needs a token."
  say "It lives for a week and publishes once; after the release, a re-run of this wizard retires it."
  replace_token=yes
  if has_secret NPM_TOKEN; then
    say "NPM_TOKEN is already set on $GH_REPO."
    confirm "Replace it with a new token (if the old one expired before the release)?" || replace_token=no
  fi
  if [[ "$replace_token" == yes ]]; then
    open_url "https://www.npmjs.com/settings/$NPM_USER/tokens"
    step "Generate New Token. Name it: legible-slides first release."
    step "Tick Bypass two-factor authentication, so the workflow can publish unattended."
    note "  npm warns about this and suggests trusted publishing. That comes after the first"
    note "  release; a short expiry keeps the risk small until then."
    step "Packages and scopes → Permissions: Read and write (publish and stage)."
    note "  'Stage only' would hold each version until you promote it by hand."
    step "Select Packages: All Packages. npm can't select a package that doesn't exist yet."
    step "Expiration: 7 days."
    step "Generate Token, then copy it from the top of the page. npm shows it once."
    ask_secret NPM_TOKEN_VALUE "Paste the token (starts with npm_):"
    if [[ "$NPM_TOKEN_VALUE" != npm_* ]]; then
      warn "That doesn't start with npm_. Saving it anyway; re-run this stage if it was a mis-paste."
    fi
    set_secret NPM_TOKEN "$NPM_TOKEN_VALUE"
    unset NPM_TOKEN_VALUE
    warn "Tag v0.1.0 within 7 days, then re-run this wizard to switch to trusted publishing."
  else
    note "Keeping the current NPM_TOKEN."
  fi
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "npm: trusted publishing, in place of the token"
if [[ "$PUBLISHED" != yes ]]; then
  say "This needs both packages on npm, so it waits for the first release."
  note "Re-run this wizard once v0.1.0 is out. Skipping ahead."
else
  say "npm will accept a version only from $GH_REPO's $RELEASE_WORKFLOW, with no token stored,"
  say "and only staged: it goes live when you approve it with 2FA."
  note "npm doesn't let this script see it, so this stage can't tell if it's done."
  trusted=no
  if confirm "Already added the trusted publisher to both packages?"; then
    trusted=yes
    note "Skipping ahead."
  else
    warn "A new trusted publisher expires unless it publishes within 2 days."
    say "  Do this stage right before you tag the next release, and approve what it stages"
    say "  the same day."
    if confirm "Tagging a release within 2 days?"; then
      for package in "${NPM_PACKAGES[@]}"; do
        open_url "https://www.npmjs.com/package/$package/access"
        step "Trusted Publisher → GitHub Actions, then fill in:"
        say "    Organization or user  ${BOLD}${GH_REPO%%/*}${RESET}"
        say "    Repository            ${BOLD}${GH_REPO#*/}${RESET}"
        say "    Workflow filename     ${BOLD}$RELEASE_WORKFLOW${RESET}"
        say "    Environment name      ${DIM}(leave empty)${RESET}"
        step "Leave Allow npm publish and Allow npm dist-tag unchecked, then Set up connection."
        note "  The workflow can then only stage. Each release waits under Staged Packages on"
        note "  npmjs.com until you approve it there with 2FA, or with npm stage approve."
        step "Publishing access → Require two-factor authentication and disallow tokens → Update."
        note "  You can still publish by hand with your 2FA, so a wrong field can't lock you out."
        pause "Press Enter once $package is done."
      done
      trusted=yes
    else
      SKIPPED+=("npm trusted publishers: re-run this wizard within 2 days of the next release")
    fi
  fi
  # Only once npm trusts the workflow: until then the token is the release's only way to publish.
  if [[ "$trusted" == yes ]] && has_secret NPM_TOKEN; then
    say "NPM_TOKEN is still on $GH_REPO, and the release no longer needs it."
    if confirm "Delete it now, and revoke it on npm?"; then
      if gh secret delete NPM_TOKEN >/dev/null 2>&1; then
        ok "deleted the NPM_TOKEN secret"
      else
        SKIPPED+=("delete the NPM_TOKEN secret: gh secret delete NPM_TOKEN --repo $GH_REPO")
        warn "Couldn't delete it through gh."
      fi
      open_url "https://www.npmjs.com/settings/$NPM_USER/tokens"
      step "Delete the token named legible-slides first release, if it hasn't expired."
    else
      SKIPPED+=("delete the NPM_TOKEN secret and revoke the npm token")
    fi
  fi
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "GitHub: a '$PYPI_ENVIRONMENT' environment"
say "PyPI only trusts a publish that runs in this environment of the release workflow."
if has_environment "$PYPI_ENVIRONMENT"; then
  note "It already exists. Skipping ahead."
elif confirm "Create the '$PYPI_ENVIRONMENT' environment on $GH_REPO now?"; then
  if gh api -X PUT "repos/$GH_REPO/environments/$PYPI_ENVIRONMENT" >/dev/null 2>&1; then
    ok "created environment $PYPI_ENVIRONMENT"
  else
    SKIPPED+=("$ENVIRONMENT_BY_HAND")
    warn "Couldn't create it through gh. Add it under Settings → Environments instead."
  fi
else
  SKIPPED+=("$ENVIRONMENT_BY_HAND")
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "PyPI: an account with two-factor auth"
say "The checks publish under your PyPI account. PyPI asks for 2FA before it lets you publish."
if confirm "Do you already have a PyPI account with two-factor auth on?"; then
  note "Skipping ahead."
else
  open_url "https://pypi.org/account/register/"
  step "Register, or sign in if you have an account, and verify your email."
  step "Account settings → Two factor authentication → add an authenticator app or security key."
  pause "Press Enter once 2FA is on."
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "PyPI: a pending trusted publisher for $PYPI_PROJECT"
say "This lets the release workflow publish with no PyPI token stored anywhere."
note "PyPI doesn't let gh or this script see it, so this stage can't tell if it's done."
if confirm "Already added the pending publisher for $PYPI_PROJECT?"; then
  note "Skipping ahead."
else
  open_url "https://pypi.org/manage/account/publishing/"
  step "Under 'Add a new pending publisher', choose GitHub, then fill in:"
  say "    PyPI Project Name   ${BOLD}$PYPI_PROJECT${RESET}"
  say "    Owner               ${BOLD}${GH_REPO%%/*}${RESET}"
  say "    Repository name     ${BOLD}${GH_REPO#*/}${RESET}"
  say "    Workflow name       ${BOLD}$RELEASE_WORKFLOW${RESET}"
  say "    Environment name    ${BOLD}$PYPI_ENVIRONMENT${RESET}"
  step "Click Add. It should show up in the list of pending publishers."
  note "It doesn't reserve the name: if someone else registers $PYPI_PROJECT first, it lapses."
  pause "Press Enter once it's listed."
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Check what's in place"
if [[ "$PUBLISHED" == yes ]]; then
  if has_secret NPM_TOKEN; then
    warn "NPM_TOKEN is still set. Trusted publishing replaces it; delete it once that works."
  else
    ok "no npm token stored: releases publish through trusted publishing"
  fi
elif has_secret NPM_TOKEN; then
  ok "NPM_TOKEN is set on $GH_REPO, for the first release"
else
  warn "NPM_TOKEN isn't set, and the first release needs it."
  SKIPPED+=("NPM_TOKEN: re-run this wizard, or gh secret set NPM_TOKEN --repo $GH_REPO")
fi
if has_environment "$PYPI_ENVIRONMENT"; then
  ok "the $PYPI_ENVIRONMENT environment exists"
else
  warn "The $PYPI_ENVIRONMENT environment is missing."
  [[ " ${SKIPPED[*]} " == *"$ENVIRONMENT_BY_HAND"* ]] || SKIPPED+=("$ENVIRONMENT_BY_HAND")
fi
# Until the first release each name should still be free. After it, each should be yours.
for package in "${NPM_PACKAGES[@]}"; do
  check_name_free npm "https://registry.npmjs.org/$package" "$package"
done
check_name_free PyPI "https://pypi.org/pypi/$PYPI_PROJECT/json" "$PYPI_PROJECT"
pause

finish
